### ISSUE TITLE
Drop `ecmaFeatures`

### ISSUE THREAD

**Issue by nomego** [Neovici/eslint-config#3]
`(node:10567) [ESLINT_LEGACY_ECMAFEATURES] DeprecationWarning: The 'ecmaFeatures' config file property is deprecated, and has no effect. (found in "@neovici")`

**Comment by cristinecula** [comment]
Where does this message occur? This config does not contain any `ecmaFeatures` property.

**Comment by dotpointer** [comment]
How is this error reproduced?

**Comment by dotpointer** [comment]
I searched the whole frontend directory and the only location I got matches on `ecmaFeatures` was in `node_modules/`. These subdirectories matched:

`babel-eslint`, `eslint`, `polymer-bundler`, `polymer-cli`

**Comment by nomego** [comment]
I got this in VSCode but might have been some workdir thing, closing.
