### ISSUE TITLE
Add `no-console`, `no-debugger` error rules

### ISSUE THREAD

**Issue by nomego** [Neovici/eslint-config#4]
We do have places in FE where we use console, but normally this is due to a forgotten console.log statement while developing/debugging.

We should error on any un-muted console statements, as well as debugger statements.

**Comment by cristinecula** [comment]
Please make sure that the auto-correct on save behavior does not "correct" the debugger statements. I run into this a while back and it was really annoying.

**Comment by dotpointer** [comment]
> Please make sure that the auto-correct on save behavior does not "correct" the debugger statements. I run into this a while back and it was really annoying.

And how do I do this?

**Comment by dotpointer** [comment]
I have no idea how to fulfill @cristinecula:s request but I have made a pull request to add the rules in #5.

**Comment by cristinecula** [comment]
@dotpointer you can add the `no-debugger` rule to the cosmoz-frontend eslint configuration and try it out there.

**Comment by dotpointer** [comment]
Fixed in #5.
